name: neuro-env
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - jupyterlab
  - scikit-learn
  - seaborn
  - scikit-learn-intelex
  - scipy=1.7
  - python=3.9
  - matplotlib
  - statsmodels
  - ipykernel
  - numba
  - pybads
  - pip
  - pip:
      - codetiming
