function h = prettyfig(h)
% prepare figure for publication
%
% h = figure handle

if nargin<1 , h = gcf; end

% set(h,  'units'         , 'centimeters' , ...  
%         'color'         , 'w'           , ...
%         'menubar'       , 'none'        , ...
%         'InvertHardcopy', 'on'           );
%     
set(h,  'units'         , 'centimeters' , ...  
        'color'         , 'w'           , ...
        'InvertHardcopy', 'on'           );