function P = collapse_notabs_7(B,k_urg,drift,t,x,y)
%COLLAPSE_NOTABS_7
%    P = COLLAPSE_NOTABS_7(B,K_URG,DRIFT,T,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    04-Aug-2022 14:58:38

t2 = drift.*t;
t3 = k_urg.*t;
t4 = t.^2;
t5 = 1.0./pi;
t6 = 1.0./t;
t7 = -x;
t8 = -y;
t11 = sqrt(2.0);
t9 = -t2;
t10 = -t3;
t12 = drift.*t11;
t13 = k_urg.*t11;
t14 = t4./2.0;
t15 = t11+1.0;
t20 = B+t2+t3+t7;
t16 = B.*t15;
t18 = B+t2+t10+y;
t19 = 1.0./sqrt(t14);
t21 = B+t9+t10+x;
t22 = B+t3+t8+t9;
t17 = -t16;
t23 = t6.*t18.*2.0;
t24 = t2+t10+t16+y;
t25 = t6.*t21.*2.0;
t26 = t2+t3+t7+t16;
t27 = t6.*t22.*2.0;
t28 = t6.*t11.*t18;
t29 = t9+t10+t16+x;
t31 = t6.*t11.*t21;
t32 = t6.*t11.*t22;
t30 = t2+t10+t17+y;
t33 = t6.*t26.*2.0;
t34 = t6.*t11.*t26;
t35 = -t34;
et1 = (t5.*t19.*exp(t18.*(t23+t31).*(-1.0./2.0)-(t21.*(t25+t28))./2.0))./2.0-(t5.*t19.*exp(t21.*(t25+t6.*t11.*t30).*(-1.0./2.0)-(t30.*(t31+t6.*t30.*2.0))./2.0).*exp(t16.*(drift+k_urg-t12+t13).*2.0))./2.0+(t5.*t19.*exp(t22.*(t27+t6.*t11.*t20).*(-1.0./2.0)-(t20.*(t32+t6.*t20.*2.0))./2.0).*exp(B.*t11.*(k_urg+t13).*4.0))./2.0-(t5.*t19.*exp(t22.*(t27+t6.*t11.*(t2+t3+t7+t17)).*(-1.0./2.0)-((t32+t6.*(t2+t3+t7+t17).*2.0).*(t2+t3+t7+t17))./2.0).*exp(B.*(drift-k_urg).*-2.0))./2.0;
et2 = t5.*t19.*exp(t18.*(t23+t35).*(-1.0./2.0)+(t26.*(t28-t33))./2.0).*exp(t16.*(-drift+k_urg+t12+t13).*2.0).*(-1.0./2.0)+(t5.*t19.*exp(t26.*(t33-t6.*t11.*t24).*(-1.0./2.0)+(t24.*(t34-t6.*t24.*2.0))./2.0).*exp(B.*(k_urg+t12./2.0+t13./2.0).*4.0))./2.0;
P = et1+et2;
